//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto2evaluacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class recursosProyecto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal recursosProyecto() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("proyecto2evaluacion.recursosProyecto", typeof(recursosProyecto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar.
        /// </summary>
        internal static string stBotonFibo {
            get {
                return ResourceManager.GetString("stBotonFibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error.
        /// </summary>
        internal static string stError {
            get {
                return ResourceManager.GetString("stError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estos son los números fibonacci hasta el número introducido: .
        /// </summary>
        internal static string stFibonacciIntroducidos {
            get {
                return ResourceManager.GetString("stFibonacciIntroducidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un número positivo :.
        /// </summary>
        internal static string stLabelFibo {
            get {
                return ResourceManager.GetString("stLabelFibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inserte un número , el resto de parámetros son inválidos.
        /// </summary>
        internal static string stringInserteNum {
            get {
                return ResourceManager.GetString("stringInserteNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número debe ser mayor de 0.
        /// </summary>
        internal static string stringMayorDe0 {
            get {
                return ResourceManager.GetString("stringMayorDe0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número introducido supera el valor maximo permitido para un entero.
        /// </summary>
        internal static string stringNoPermitido {
            get {
                return ResourceManager.GetString("stringNoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inserte un valor adecuado que no sobrepase el valor maximo permitido por visual stuido, ni con decimales.
        /// </summary>
        internal static string stValoresPermitidos {
            get {
                return ResourceManager.GetString("stValoresPermitidos", resourceCulture);
            }
        }
    }
}
